Add tests to update script

diff --git a/collector/.deploy/make-update b/collector/.deploy/make-update
--- a/collector/.deploy/make-update
+++ b/collector/.deploy/make-update
@@ -4,7 +4,22 @@ set -ex
 
 dir="$(cd "$(dirname "$0")" && pwd)"
 
+"$dir/../run-test"
+
 "$dir/docker-build"
+
+log_file="$(mktemp)"
+"$dir/docker-test" | tee "$log_file"
+
+set +ex
+errors="$(grep ERROR "$log_file")"
+set -ex
+
+if [[ -n "$errors" ]]; then
+    echo "$errors"
+    exit 1
+fi
+
 "$dir/docker-push"
 
 ansible-playbook -i ~/.private/home-server-inventory "$dir/update-on-server.yml"
